export const LEGISLATION_STATUS = {
  DRAFT_UPLOADED: "DRAF_MASUK",
  PUBLIC_OPINION: "MASA_OPINI",
  VERIFICATION: "VERIFIKASI",
  REVISED: "REVISI",
} as const;

export const PROPOSAL_STATUS = {
  PEMERIKSAAN_DATA: "PEMERIKSAAN_DATA",
  PEMILIHAN_PRIORITAS: "PEMILIHAN_PRIORITAS",
  ALOKASI_DANA: "ALOKASI_DANA",
  SEDANG_DIBANGUN: "SEDANG_DIBANGUN",
  PROYEK_SELESAI: "PROYEK_SELESAI",
} as const;

export const STATUS_LABELS: Record<string, string> = {
  [LEGISLATION_STATUS.DRAFT_UPLOADED]: "Draf Masuk",
  [LEGISLATION_STATUS.PUBLIC_OPINION]: "Masa Opini Publik",
  [LEGISLATION_STATUS.VERIFICATION]: "Proses Verifikasi",
  [LEGISLATION_STATUS.REVISED]: "Direvisi",

  [PROPOSAL_STATUS.PEMERIKSAAN_DATA]: "Pemeriksaan Data",
  [PROPOSAL_STATUS.PEMILIHAN_PRIORITAS]: "Pemilihan Prioritas",
  [PROPOSAL_STATUS.ALOKASI_DANA]: "Alokasi Dana",
  [PROPOSAL_STATUS.SEDANG_DIBANGUN]: "Sedang Dibangun",
  [PROPOSAL_STATUS.PROYEK_SELESAI]: "Proyek Selesai",
};
