export const LEGISLATION_STATUS = {
  DRAFT_UPLOADED: "DRAFT_UPLOADED",
  PUBLIC_OPINION: "PUBLIC_OPINION",
  VERIFICATION: "VERIFICATION",
  REVISED: "REVISED",
  NO_REVISION: "NO_REVISION",
} as const;

export const PROPOSAL_STATUS = {
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  VOTING_PHASE: "VOTING_PHASE",
  BUDGETING: "BUDGETING",
  COMPLETED: "COMPLETED",
} as const;

export type LegislationStatus = keyof typeof LEGISLATION_STATUS;
export type ProposalStatus = keyof typeof PROPOSAL_STATUS;

export const STATUS_LABELS: Record<string, string> = {
  [LEGISLATION_STATUS.DRAFT_UPLOADED]: "Draf Masuk",
  [LEGISLATION_STATUS.PUBLIC_OPINION]: "Masa Opini Publik",
  [LEGISLATION_STATUS.VERIFICATION]: "Proses Verifikasi",
  [LEGISLATION_STATUS.REVISED]: "Direvisi",
  [LEGISLATION_STATUS.NO_REVISION]: "Tidak Ada Revisi",

  [PROPOSAL_STATUS.SUBMITTED]: "Usulan Masuk",
  [PROPOSAL_STATUS.UNDER_REVIEW]: "Sedang Ditinjau",
  [PROPOSAL_STATUS.VOTING_PHASE]: "Masa Voting",
  [PROPOSAL_STATUS.BUDGETING]: "Masuk Anggaran",
  [PROPOSAL_STATUS.COMPLETED]: "Selesai Dibangun",
};
